import re, json

SRC = "/data/data/com.termux/files/usr/tmp/awesome-selfhosted/README.md"
FAILS = "/data/data/com.termux/files/usr/tmp/link-check-results2.json"
OUT = "/data/data/com.termux/files/usr/tmp/awesome-selfhosted/data.js"

t = open(SRC, encoding="utf-8", errors="ignore").read()
fails = set(u for u, _ in json.load(open(FAILS))["fails"])

# cut at "## Software" and stop before "## Non-Free" / "## External"
m = re.search(r'^## Software', t, re.M)
if not m:
    print("Software section not found"); raise SystemExit(1)
body = t[m.start():]
end = re.search(r'^## (Non-Free|External|Contributing|License)', body, re.M)
if end:
    body = body[:end.start()]

lines = body.splitlines()
cats = []
cur = None
entry_re = re.compile(r'^- \[([^\]]+)\]\(([^)]+)\)\s*-?\s*(.*)$')

for ln in lines:
    if ln.startswith('### '):
        cur = {"name": ln[4:].strip(), "items": []}
        cats.append(cur)
        continue
    if cur is None:
        continue
    mm = entry_re.match(ln.strip())
    if not mm:
        continue
    name, url, rest = mm.group(1), mm.group(2), mm.group(3)
    if url in fails:
        continue  # skip dead link
    # extract source code url
    src = re.search(r'\[Source Code\]\(([^)]+)\)', rest)
    src_url = src.group(1) if src else ""
    if src_url in fails:
        src_url = ""  # don't link dead source
    # license + platform tags
    tags = re.findall(r'`([^`]+)`', rest)
    desc = re.sub(r'\s*\(\[Source Code\]\([^)]+\)\)', '', rest)
    desc = re.sub(r'`[^`]+`', '', desc).strip(' -–—')
    desc = re.sub(r'\s+', ' ', desc).strip()
    item = {
        "name": name,
        "url": url,
        "src": src_url,
        "desc": desc,
        "tags": tags,
    }
    cur["items"].append(item)

cats = [c for c in cats if c["items"]]
total = sum(len(c["items"]) for c in cats)
print(f"categories: {len(cats)} · items (live links only): {total}")

with open(OUT, "w") as f:
    f.write("// Generated by generate.py — only live links (dead links filtered out)\n")
    f.write("window.SELFHOST_DATA = ")
    json.dump(cats, f, ensure_ascii=False, indent=1)
    f.write(";\n")
print("written", OUT)
